on:
  push:
  workflow_dispatch:

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # - name: Pull & update submodules recursively
      #   shell: bash
      #   run: |
      #     git submodule update --init --recursive
      #     git submodule update --recursive --remote

      - name: Check frontend
        run: git diff --quiet HEAD^ HEAD ./frontend

      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install

      - name: Log
        run: echo "Log"
