on:
  push:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - id: check
        name: Check frontend
        run: git --no-pager diff HEAD^ HEAD -- ./frontend | grep diff

      - name: Build
        run: |
          cd frontend
          npm i
          npm run build
          ls -l build
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_KEY }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID }} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID }} #Required
